// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7x6cKW6OKMT2dmDjHvAZP2WSJdryVSbA',
    appId: '1:370018809773:web:df4f6644aa427a6e8d5324',
    messagingSenderId: '370018809773',
    projectId: 'cryptolistapp-2a437',
    authDomain: 'cryptolistapp-2a437.firebaseapp.com',
    storageBucket: 'cryptolistapp-2a437.appspot.com',
    measurementId: 'G-4J95ERGLHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBals7yCKzZUG6himtAz3D0zrqaEfJtkr4',
    appId: '1:370018809773:android:322023b4a8319c038d5324',
    messagingSenderId: '370018809773',
    projectId: 'cryptolistapp-2a437',
    storageBucket: 'cryptolistapp-2a437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBcS18DMSW9VPKaSB-70C8TVH2N43Urk',
    appId: '1:370018809773:ios:c62cbc269a763ae58d5324',
    messagingSenderId: '370018809773',
    projectId: 'cryptolistapp-2a437',
    storageBucket: 'cryptolistapp-2a437.appspot.com',
    iosBundleId: 'com.example.cryptorienciesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBcS18DMSW9VPKaSB-70C8TVH2N43Urk',
    appId: '1:370018809773:ios:b2dad5229ee62f408d5324',
    messagingSenderId: '370018809773',
    projectId: 'cryptolistapp-2a437',
    storageBucket: 'cryptolistapp-2a437.appspot.com',
    iosBundleId: 'com.example.cryptorienciesApp.RunnerTests',
  );
}
